services:
  web:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      chrome:
        condition: service_healthy
    command: >
      sh -c "python -m flask run --host=0.0.0.0"

  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://chrome:4444" ]
      interval: 10s
      timeout: 5s
      retries: 3